config/routes.rb
Rails.application.routes.draw do
  mount API::BaseAPI => 'api'
  mount GrapeSwaggerRails::Engine => 'swagger'

  devise_for :users

  root to: 'products#index'
  resources :products, only: %i[index]
  patch '/users/upgrade_to_premium', to: 'users#upgrade_to_premium', as: :upgrade_to_premium

  namespace :admin do
    resources :users, only: %i[index update]
    resources :products, only: %i[index show create new edit update] do
      delete :destroy_image, on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {
    normal: 0,
    premium: 300,
    admin: 700,
    owner: 999
  }

  def discount_percent
    case role
    when 'normal'
      0
    else
      10
    end
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    layout 'admin'
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::BaseController
    before_action :authorize_action
    before_action :set_product, only: %i[show edit update destroy destroy_image]

    def index
      @products = Product.order(id: :asc).with_attached_images.page(page).per(per)
    end

    def show; end

    def create
      @product = Product.create(product_params)
      redirect_to admin_product_path(@product)
    end

    def new
      @product = Product.new
    end

    def update
      @product.update(product_params)
      redirect_to admin_product_path(@product)
    end

    def edit; end

    def destroy_image
      @image = @product.images.find(params[:image_id])
      @image.purge
      redirect_to admin_product_path(@product)
    end

    private

    def authorize_action
      policy_action = "#{action_name}?"
      authorize Product, policy_action, policy_class: Admin::ProductPolicy
    end

    def set_product
      @product = @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, images: [])
    end

    def page
      params[:page] || 1
    end

    def per
      params[:per] || 10
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    def index
      @users = User.page(1).per(10)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError do |_error|
    render file: 'public/403.html'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.with_attached_images.page(1).per(12)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def upgrade_to_premium
    authorize User, :upgrade_to_premium?

    current_user.update(role: :premium)

    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/link_helper.rb
module LinkHelper
  def link_to_admin
    return nil unless current_user.admin? || current_user.owner?
    return nil if controller.class < Admin::BaseController

    link_to('Go to Admin', admin_products_path, class: 'w3-bar-item w3-button')
  end

  def link_to_website
    return nil if controller.class == ProductsController

    link_to('Go to Website', products_path, class: 'w3-bar-item w3-button')
  end

  def link_to_admin_or_website
    controller.class < Admin::BaseController ? link_to_website : link_to_admin
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def product_default_image(product, resize: product_image_default_size)
    image = product.images.first
    image.nil? ? nil : image.variant(resize: resize)
  end

  def product_image_default_size
    '100x100'
  end
end

app/helpers/ui_helper.rb
module UiHelper
  def default_button_class
    'w3-button w3-section w3-teal w3-ripple'
  end
end

app/helpers/user_helper.rb
module UserHelper
  def upgrade_to_premium_button
    return nil unless current_user.normal?

    button_class = 'w3-button w3-section w3-teal w3-ripple'
    button_to('Upgrade to premium', upgrade_to_premium_path, method: :patch, class: button_class)
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <p>
    <%= f.text_field :name, required: true, class: 'w3-input' %>
    <%= f.label :name %>
  </p>
  <p>
    <%= f.number_field :price, step: 1, class: 'w3-input' %>
    <%= f.label :price, required: true %>
  </p>
  <%= f.submit class: default_button_class %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="w3-container" style="width: 50%; margin: auto;">
  <%= render 'form' %>
  <%= link_to('Back', admin_product_path(@product)) %>
</div>

app/views/admin/products/index.html.erb
<h2> Products </h2>
<p>
  <%= button_to('New product', new_admin_product_path, method: :get, class: default_button_class) %>
</p>
<table class="w3-table-all">
  <thead>
    <tr class="w3-grey">
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to(product.name, admin_product_path(product)) %></td>
        <td><%= product.price %></td>
        <% image = product_default_image(product) %>
        <td><%= image_tag(image) if image %></td>
    <% end %>
  </tbody>
</table>

<div class="w3-center">
  <%= paginate(@products) %>
  <%= page_entries_info(@products) %>
</div>

app/views/admin/products/new.html.erb
<div class="w3-container" style="width: 50%; margin: auto;">
  <%= render 'form' %>
  <%= button_to('Back', admin_products_path, method: :get, class: default_button_class) %>
</div>

app/views/admin/products/show.html.erb
<p>
  <strong>Name: </strong><%= @product.name %>
</p>

<p>
  <strong>Price: </strong><%= @product.price %>
</p>

<%= form_for [:admin, @product] do |f| %>
  <p>
    <%= f.file_field :images, multiple: true, required: true, direct_upload: true, accept: 'image/png,image/jpeg' %>
    <%= f.submit 'Add image' %>
  </p>
<% end %>

<div style="display: flex; flex-flow: row wrap;">
  <% @product.images.each do |image| %>
    <div class="w3-padding">
      <%= image_tag(image.variant(resize: product_image_default_size), style: 'width: 100px; height: 100px') %>
      <p class="w3-container">
        <%= link_to('Delete', destroy_image_admin_product_path(@product, image_id: image.id), method: :delete) %>
      </p>
    </div>
  <% end %>
</div>

<p>
  <%= link_to('Edit', edit_admin_product_path(@product)) %> |
  <%= link_to('Back', admin_products_path) %>
</p>

app/views/admin/users/index.html.erb
<h2> Users </h2>
<%=
  react_component(
    'AdminUsersContainer',
    currentUser: current_user,
    users: @users,
    currentPage: @users.current_page,
    totalPages: @users.total_pages,
    perPage: @users.limit_value,
    totalCount: @users.total_count,
    pageEntriesInfo: page_entries_info(@users)
  )
%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembershipSystem Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <div style="height: 38px">
        <%= render 'shared/nav' %>
      </div>
    <% end %>
    <%= render 'shared/flash' %>
    <%= render 'shared/admin_sidebar' %>
    <div class="w3-main w3-container" style="margin-left: 200px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembershipSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <div style="height: 38px">
        <%= render 'shared/nav' %>
      </div>
    <% end %>
    <%= render 'shared/flash' %>
    <div class="w3-main w3-content w3-padding">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<%= upgrade_to_premium_button %>

<%= react_component('ProductsContainer', currentUser: current_user, data: Entity::V1::PaginatedProduct.represent(@products, user: current_user).as_json) %>

app/views/shared/_admin_nav.html.erb
<div class="w3-sidebar w3-bar-block" style="wdith: 15%">
  <%= link_to('Users', admin_users_path, class: 'w3-bar-item w3-button') %>
  <%= link_to('Products', admin_products_path, class: 'w3-bar-item w3-button') %>
</div>

app/views/shared/_admin_sidebar.html.erb
<div class="w3-sidebar w3-bar-block w3-collapse w3-card" style="width: 200px">
  <%= link_to('Users', admin_users_path, class: 'w3-bar-item w3-button') %>
  <%= link_to('Products', admin_products_path, class: 'w3-bar-item w3-button') %>
</div>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="w3-container w3-blue w3-card-4">
    <p><%= notice %></p>
  </div>
<% end %>
<% if alert %>
  <div class="w3-container w3-red w3-card-4">
    <p><%= alert %></p>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div class="w3-top">
  <div class="w3-bar w3-black">
    <div style="float: right">
      <span class="w3-bar-item">
        Email: <%= current_user.email %> | Membership: <%= current_user.role %>
      </span>
      <%= link_to_admin_or_website %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'w3-bar-item w3-button') %>
    </div>
  </div>
</div>